router: add saving of background service statuses
This patch introduce the ability for the user to access occurred errors
and states of the background services via 'vshard.router.info()'.

Closes #107

@TarantoolBot document
Title: vshard.router.info() new option

Since 0.1.22 `vshard.router.info()` accepts the table of opts which
can be used to control, which additional info to return. Currently,
only one option is available: `with_services`

```Lua
> vshard.router.info({with_services = true})
---
...
  services:
    failover:
      status: ok
      error: Error during failovering
      activity: idling
      status_idx: 2
    discovery:
      status: ok
      activity: idling
      status_idx: 3
```