error: add __tostring method for string objects
__Tostring is used to print an error in readable format to log,
instead of format like 'table0x21r12412'.