storage: add saving of background service statuses
This patch introduce the ability for the user to access occurred errors
and states of the background services via 'vshard.storage.info()'.

Part of #107

@TarantoolBot document
Title: vshard.storage.info() new option

Since 0.1.22 `vshard.storage.info()` accepts the table of opts which
can be used to control, which additional info to return. Currently,
only one option is available: `with_services`:

```Lua
> vshard.storage.info({with_services = true})
---
...
  services:
    gc:
      status: ok
      error: Error during garbage collection step
      activity: idling
      status_idx: 2
    recovery:
      status: ok
      activity: idling
      status_idx: 5
```