error: add support of alert objects creation
Storage.info() uses many stringified error codes. Some of them already
exists in vshard.error.code. And all alert messages are inlined. But it
does not allow to reuse them for router.info(), and leads to errors like
mismatch error messages in different files.

Move new error codes to vshard.error, and define there error message
templates for error codes, which are used for alerts.

Needed for #6 #9 #20