error: support stacked box errors
Box errors can be stacked via 'prev' member. Such errors didn't
raise any exceptions in vshard, but vshard.error.box() wouldn't
unpack any errors beyond the first one.

The patch makes so vshard.error.box() walks the whole error stack.

It is done to be consistent with a future patch which will use
'prev' field for vshard errors too, thus producing stacks of
errors as Lua tables.

That in turn is needed in order to return more than one error from
vshard.storage.call() which will be able to fail both user
function and bucket unref.

Needed for #173