error: introduce is_timeout
It's needed to check, whether the error was a timeout or not in the
following commit. Let's move this function from vtest to error module.

Needed for #426

NO_DOC=internal