error: introduce is_vshard_not_ready and unwrap_vshard_error
Before this patch
1) the logic of determining whether a storage error is retryable was
   located only in `can_backoff_after_error`.
2) the logic of extracting the vshard error from the `LuajitError` or
   `ClientError` wrapper was located only in `replica_call`.

As in next patches we need to add this logic in other places, we introduce
some new helper functions - `is_vshard_not_ready` and
`unwrap_vshard_error`.

Needed for tarantool/vshard#632

NO_TEST=refactoring
NO_DOC=refactoring