error: add more details for some errors
Storage.info() uses these errors with no details, because it considers only
its own replicaset. But router.info() will examine many replicasets. And
it requires to add replicaset UUID to some errors.

Needed for #6, #19, #20