error: fix conflicting member names
This patch solves the problem with conflicting
arguments in the error module.

The arguments in the 'ROUTER_ALREADY_EXISTS'
and 'ROUTER_CFG_IS_IN_PROGRESS' errors have been
renamed to 'router_name'. The 'name' field in the
error object is already in use.

NO_DOC=undocumented behavior